// The fastest route through each level, worked out once by the A* and kept.
//
// It is a pure function of the engine and the level data, exactly like the
// trained genomes are, so it belongs in a file next to them rather than in the
// player's browser: searching a level takes a few seconds, and doing that
// between frames made the first seconds of a replay stutter badly.
//
// Regenerated by `npm run train-agent`. A test replays each route and fails
// when it no longer finishes its level, which is what catches a stale file
// after a physics or level change.
import routes from "./routes.json";
import { NO_INPUT, type Input } from "../engine";

/** One frame of held buttons, small enough to be worth storing as a number. */
const BUTTONS = {
  left: 1,
  right: 2,
  jumpHeld: 4,
  jumpPressed: 8,
  run: 16,
  down: 32,
} as const;

export function encodeInput(input: Input): number {
  let code = 0;
  for (const [button, bit] of Object.entries(BUTTONS)) {
    if (input[button as keyof typeof BUTTONS]) {
      code |= bit;
    }
  }
  return code;
}

export function decodeInput(code: number): Input {
  return {
    ...NO_INPUT,
    left: (code & BUTTONS.left) !== 0,
    right: (code & BUTTONS.right) !== 0,
    jumpHeld: (code & BUTTONS.jumpHeld) !== 0,
    jumpPressed: (code & BUTTONS.jumpPressed) !== 0,
    run: (code & BUTTONS.run) !== 0,
    down: (code & BUTTONS.down) !== 0,
  };
}

export type StoredRoute = { level: number; frames: number; inputs: number[] };

export const ROUTES: StoredRoute[] = routes.routes;

export function routeFor(levelIndex: number): Input[] | null {
  const stored = ROUTES.find((route) => route.level === levelIndex);
  return stored === undefined ? null : stored.inputs.map(decodeInput);
}
