// Hand-authored pixel art (original), not derived from any Nintendo asset.
// Grid legend: space = transparent, letters index into PALETTE below.
export const PALETTE: Record<string, string> = {
  'R': '#d82828',
  'D': '#8c1414',
  'S': '#ffcc99',
  'M': '#5c3a21',
  'B': '#2a52c4',
  'C': '#193282',
  'Y': '#ffd84a',
  'W': '#ffffff',
  'K': '#141414',
}

export type Frame = string[]

export const MarioIdle: Frame = [
  '     DRRRRRRR   ',
  '    RRRRRRRRRR  ',
  '   RRRRRRRRRRRR ',
  '  RRRRRRRRRRRRRR',
  '   MMMSSSSSSS   ',
  '  MSSSSSSSSSS   ',
  '  MSSSKWSSSSS   ',
  '  MMMMSSSSS     ',
  '  MMSSSSSSSS    ',
  '   SSSSSSSS     ',
  '    RRRRRR      ',
  '   RRRRRRRR     ',
  '  RRBBBBBBRR    ',
  ' WRBBYBBYBBRW   ',
  ' WWBBBBBBBBW    ',
  ' WWCBBBBBBCW    ',
  '   CBBBBBBC     ',
  '   CBBBBBBC     ',
  '   BB    BB     ',
  '   BB    BB     ',
  '  MMM    MMM    ',
  ' MMMM    MMMM   ',
  ' MMMM    MMMM   ',
  '                ',
]

export const MarioWalk1: Frame = [
  '     DRRRRRRR   ',
  '    RRRRRRRRRR  ',
  '   RRRRRRRRRRRR ',
  '  RRRRRRRRRRRRRR',
  '   MMMSSSSSSS   ',
  '  MSSSSSSSSSS   ',
  '  MSSSKWSSSSS   ',
  '  MMMMSSSSS     ',
  '  MMSSSSSSSS    ',
  '   SSSSSSSS     ',
  '    RRRRRR      ',
  '   RRRRRRRR     ',
  '  RRBBBBBBRR    ',
  ' WRBBYBBYBBRW   ',
  ' WWBBBBBBBBW    ',
  ' WWCBBBBBBCW    ',
  '   CBBBBBBC     ',
  '   CBBBBBB      ',
  '  MMM   CBB     ',
  ' MMMM    BB     ',
  ' MMMM   CBBC    ',
  '        MMMM    ',
  '        MMMM    ',
  '                ',
]

export const MarioWalk2: Frame = [
  '     DRRRRRRR   ',
  '    RRRRRRRRRR  ',
  '   RRRRRRRRRRRR ',
  '  RRRRRRRRRRRRRR',
  '   MMMSSSSSSS   ',
  '  MSSSSSSSSSS   ',
  '  MSSSKWSSSSS   ',
  '  MMMMSSSSS     ',
  '  MMSSSSSSSS    ',
  '   SSSSSSSS     ',
  '    RRRRRR      ',
  '   RRRRRRRR     ',
  '  RRBBBBBBRR    ',
  ' WRBBYBBYBBRW   ',
  ' WWBBBBBBBBW    ',
  ' WWCBBBBBBCW    ',
  '   CBB   CBB    ',
  '   CBB   CBB    ',
  '   BB    MMM    ',
  '   BB   MMMM    ',
  '  CBBC  MMMM    ',
  ' MMMM           ',
  ' MMMM           ',
  '                ',
]

export const MarioJump: Frame = [
  '     DRRRRRRR   ',
  '    RRRRRRRRRR  ',
  '   RRRRRRRRRRRR ',
  '  RRRRRRRRRRRRRR',
  '   MMMSSSSSSS   ',
  '  MSSSSSSSSSS   ',
  '  MSSSKWSSSSS   ',
  '  MMMMSSSSS     ',
  ' SMMSSSSSSSS    ',
  ' SSSSSSSSS      ',
  '    RRRRRR   S  ',
  '   RRRRRRRR SW  ',
  '  RRBBBBBBRRW   ',
  ' WRBBYBBYBBRW   ',
  ' WWBBBBBBBBW    ',
  ' WWCBBBBBBCW    ',
  '  CBBBBBBBBC    ',
  '  CBB    CBB    ',
  '  BB      BB    ',
  ' MMM      MMM   ',
  ' MMM      MMM   ',
  '                ',
  '                ',
  '                ',
]

export const Goomba: Frame = [
  '                ',
  '                ',
  '    MMMMMMMM    ',
  '  MMMMMMMMMMMM  ',
  ' MMMMMMMMMMMMMM ',
  ' MMMDDDDDDDDMM  ',
  'MMMDSKKSSKKSDMM ',
  'MMMDSKKSSKKSDMM ',
  'MMMMSSSSSSSSDMM ',
  'MMMMMSSSSSSDMM  ',
  ' MMMMMMMMMMMM   ',
  ' MMMMMMMMMMMM   ',
  '  MMMMMMMMMM    ',
  '  MMMMMMMMMM    ',
  '  KKK    KKK    ',
  ' KKKK    KKKK   ',
  '                ',
  '                ',
]

export const GoombaSquashed: Frame = [
  '                ',
  '                ',
  '                ',
  '                ',
  '                ',
  '                ',
  '                ',
  '                ',
  '                ',
  '                ',
  '                ',
  '                ',
  '  MMMMMMMMMM    ',
  ' MMMMMMMMMMMM   ',
  'MMMDDDDDDDDMM   ',
  'MMMMMMMMMMMM    ',
  ' KK        KK   ',
  '                ',
]
