// Hand-authored pixel art (original), not derived from any Nintendo asset.
// Grid legend: space = transparent, letters index into PALETTE below.
// Deliberately possibly-undefined: a space, or any letter not listed here,
// is transparent rather than a colour.
export const PALETTE: Record<string, string | undefined> = {
  'R': '#d82828',
  'D': '#8c1414',
  'S': '#ffcc99',
  'M': '#5c3a21',
  'B': '#2a52c4',
  'C': '#193282',
  'Y': '#ffd84a',
  'W': '#ffffff',
  'K': '#141414',
  'G': '#3aa33a',
  'g': '#1f6b1f',
  'L': '#7ad07a',
  'O': '#e8a020',
}

export type Frame = string[]

export const SmallIdle: Frame = [
  '    DRRRRRRR    ',
  '   RRRRRRRRRR   ',
  '  RRRRRRRRRRRRR ',
  '   MMSSSSSSS    ',
  '  MSSSKWSSSS    ',
  '  MMMMSSSSS     ',
  '   SSSSSSSS     ',
  '    RRRRRR      ',
  '  WRRBBBBRRW    ',
  ' WWRBBYBBRWW    ',
  ' WW BBBBBB WW   ',
  '   CBBBBBBC     ',
  '   BB    BB     ',
  '  MMM    MMM    ',
  ' MMMM    MMMM   ',
  '                ',
]

export const SmallWalk1: Frame = [
  '    DRRRRRRR    ',
  '   RRRRRRRRRR   ',
  '  RRRRRRRRRRRRR ',
  '   MMSSSSSSS    ',
  '  MSSSKWSSSS    ',
  '  MMMMSSSSS     ',
  '   SSSSSSSS     ',
  '    RRRRRR      ',
  '  WRRBBBBRRW    ',
  ' WWRBBYBBRWW    ',
  ' WW BBBBBB WW   ',
  '   CBBBBBB      ',
  '  MMM   CBB     ',
  ' MMMM    BB     ',
  ' MMMM   MMMM    ',
  '        MMMM    ',
]

export const SmallWalk2: Frame = [
  '    DRRRRRRR    ',
  '   RRRRRRRRRR   ',
  '  RRRRRRRRRRRRR ',
  '   MMSSSSSSS    ',
  '  MSSSKWSSSS    ',
  '  MMMMSSSSS     ',
  '   SSSSSSSS     ',
  '    RRRRRR      ',
  '  WRRBBBBRRW    ',
  ' WWRBBYBBRWW    ',
  ' WW BBBBBB WW   ',
  '   CBB  CBB     ',
  '   BB   MMM     ',
  '  CBBC MMMM     ',
  ' MMMM  MMMM     ',
  ' MMMM           ',
]

export const SmallJump: Frame = [
  '    DRRRRRRR    ',
  '   RRRRRRRRRR   ',
  '  RRRRRRRRRRRRR ',
  '   MMSSSSSSS    ',
  '  MSSSKWSSSS    ',
  ' SMMMSSSSSS     ',
  ' SSSSSSSSS   S  ',
  '    RRRRRR  SW  ',
  '  WRRBBBBRRWW   ',
  ' WWRBBYBBRWW    ',
  ' WW BBBBBB WW   ',
  '  CBBBBBBBBC    ',
  '  BB      BB    ',
  ' MMM      MMM   ',
  ' MMM      MMM   ',
  '                ',
]

export const BigIdle: Frame = [
  '     DRRRRRRR   ',
  '    RRRRRRRRRR  ',
  '   RRRRRRRRRRRR ',
  '  RRRRRRRRRRRRRR',
  '   MMMSSSSSSS   ',
  '  MSSSSSSSSSS   ',
  '  MSSSKWSSSSS   ',
  '  MMMMSSSSS     ',
  '  MMSSSSSSSS    ',
  '   SSSSSSSS     ',
  '    RRRRRR      ',
  '   RRRRRRRR     ',
  '  RRBBBBBBRR    ',
  ' WRBBYBBYBBRW   ',
  ' WWBBBBBBBBW    ',
  ' WWCBBBBBBCW    ',
  ' WWBBBBBBBBW    ',
  ' WWCBBBBBBCW    ',
  ' WWBBBBBBBBW    ',
  ' WWCBBBBBBCW    ',
  '   CBBBBBBC     ',
  '   CBBBBBBC     ',
  '   BB    BB     ',
  '   BB    BB     ',
  '   BB    BB     ',
  '   BB    BB     ',
  '   BB    BB     ',
  '   BB    BB     ',
  '  MMM    MMM    ',
  ' MMMM    MMMM   ',
  ' MMMM    MMMM   ',
  '                ',
]

export const BigWalk1: Frame = [
  '     DRRRRRRR   ',
  '    RRRRRRRRRR  ',
  '   RRRRRRRRRRRR ',
  '  RRRRRRRRRRRRRR',
  '   MMMSSSSSSS   ',
  '  MSSSSSSSSSS   ',
  '  MSSSKWSSSSS   ',
  '  MMMMSSSSS     ',
  '  MMSSSSSSSS    ',
  '   SSSSSSSS     ',
  '    RRRRRR      ',
  '   RRRRRRRR     ',
  '  RRBBBBBBRR    ',
  ' WRBBYBBYBBRW   ',
  ' WWBBBBBBBBW    ',
  ' WWCBBBBBBCW    ',
  ' WWBBBBBBBBW    ',
  ' WWCBBBBBBCW    ',
  ' WWBBBBBBBBW    ',
  ' WWCBBBBBBCW    ',
  '   CBBBBBBC     ',
  '   CBBBBBB      ',
  '  MMM   CBB     ',
  ' MMMM    BB     ',
  '  MMM   CBB     ',
  ' MMMM    BB     ',
  '  MMM   CBB     ',
  ' MMMM    BB     ',
  ' MMMM   CBBC    ',
  '        MMMM    ',
  '        MMMM    ',
  '                ',
]

export const BigWalk2: Frame = [
  '     DRRRRRRR   ',
  '    RRRRRRRRRR  ',
  '   RRRRRRRRRRRR ',
  '  RRRRRRRRRRRRRR',
  '   MMMSSSSSSS   ',
  '  MSSSSSSSSSS   ',
  '  MSSSKWSSSSS   ',
  '  MMMMSSSSS     ',
  '  MMSSSSSSSS    ',
  '   SSSSSSSS     ',
  '    RRRRRR      ',
  '   RRRRRRRR     ',
  '  RRBBBBBBRR    ',
  ' WRBBYBBYBBRW   ',
  ' WWBBBBBBBBW    ',
  ' WWCBBBBBBCW    ',
  ' WWBBBBBBBBW    ',
  ' WWCBBBBBBCW    ',
  ' WWBBBBBBBBW    ',
  ' WWCBBBBBBCW    ',
  '   CBB   CBB    ',
  '   CBB   CBB    ',
  '   BB    MMM    ',
  '   BB   MMMM    ',
  '   BB    MMM    ',
  '   BB   MMMM    ',
  '   BB    MMM    ',
  '   BB   MMMM    ',
  '  CBBC  MMMM    ',
  ' MMMM           ',
  ' MMMM           ',
  '                ',
]

export const BigJump: Frame = [
  '     DRRRRRRR   ',
  '    RRRRRRRRRR  ',
  '   RRRRRRRRRRRR ',
  '  RRRRRRRRRRRRRR',
  '   MMMSSSSSSS   ',
  '  MSSSSSSSSSS   ',
  '  MSSSKWSSSSS   ',
  '  MMMMSSSSS     ',
  ' SMMSSSSSSSS    ',
  ' SSSSSSSSS      ',
  '    RRRRRR   S  ',
  '   RRRRRRRR SW  ',
  '  RRBBBBBBRRW   ',
  ' WRBBYBBYBBRW   ',
  ' WWBBBBBBBBW    ',
  ' WWCBBBBBBCW    ',
  ' WWBBBBBBBBW    ',
  ' WWCBBBBBBCW    ',
  ' WWBBBBBBBBW    ',
  ' WWCBBBBBBCW    ',
  '  CBBBBBBBBC    ',
  '  CBB    CBB    ',
  '  BB      BB    ',
  ' MMM      MMM   ',
  '  BB      BB    ',
  ' MMM      MMM   ',
  '  BB      BB    ',
  ' MMM      MMM   ',
  ' MMM      MMM   ',
  '                ',
  '                ',
  '                ',
]

export const BigCrouch: Frame = [
  '                ',
  '                ',
  '                ',
  '                ',
  '                ',
  '                ',
  '                ',
  '                ',
  '     DRRRRRRR   ',
  '    RRRRRRRRRR  ',
  '   RRRRRRRRRRRR ',
  '  RRRRRRRRRRRRRR',
  '   MMMSSSSSSS   ',
  '  MSSSSSSSSSS   ',
  '  MSSSKWSSSSS   ',
  '  MMMMSSSSS     ',
  '  MMSSSSSSSS    ',
  '   SSSSSSSS     ',
  '  WRRRRRRRRW    ',
  ' WWRBBBBBBRWW   ',
  ' WWBBYBBYBBWW   ',
  '   CBBBBBBC     ',
  '  CBBBBBBBBC    ',
  '  MMM    MMM    ',
  ' MMMM    MMMM   ',
  ' MMMM    MMMM   ',
  '                ',
  '                ',
  '                ',
  '                ',
  '                ',
  '                ',
]

export const Goomba: Frame = [
  '                ',
  '                ',
  '    MMMMMMMM    ',
  '  MMMMMMMMMMMM  ',
  ' MMMMMMMMMMMMMM ',
  ' MMMDDDDDDDDMM  ',
  'MMMDSKKSSKKSDMM ',
  'MMMDSKKSSKKSDMM ',
  'MMMMSSSSSSSSDMM ',
  'MMMMMSSSSSSDMM  ',
  ' MMMMMMMMMMMM   ',
  ' MMMMMMMMMMMM   ',
  '  MMMMMMMMMM    ',
  '  MMMMMMMMMM    ',
  '  KKK    KKK    ',
  ' KKKK    KKKK   ',
  '                ',
  '                ',
]

export const GoombaSquashed: Frame = [
  '                ',
  '                ',
  '                ',
  '                ',
  '                ',
  '                ',
  '                ',
  '                ',
  '                ',
  '                ',
  '                ',
  '                ',
  '  MMMMMMMMMM    ',
  ' MMMMMMMMMMMM   ',
  'MMMDDDDDDDDMM   ',
  'MMMMMMMMMMMM    ',
  ' KK        KK   ',
  '                ',
]

// A koopa: green shell, yellow feet, and it walks off ledges like the rest.
export const Koopa: Frame = [
  '      GGGG      ',
  '     GGGGGG     ',
  '    GGWKWGGG    ',
  '    GGGGGGOO    ',
  '     GGGGGG     ',
  '   ggGGGGGGgg   ',
  '  ggGGLLLLGGgg  ',
  ' ggGGLLGGLLGGgg ',
  ' gGGLLGGGGLLGGg ',
  ' gGGGLLGGLLGGGg ',
  ' ggGGGLLLLGGGgg ',
  '  ggGGGGGGGGgg  ',
  '   gggggggggg   ',
  '  WWWWWWWWWWWW  ',
  '   OOO    OOO   ',
  '  OOOO    OOOO  ',
]

// The same shell with nobody in it, which is what you kick around.
export const KoopaShell: Frame = [
  '                ',
  '                ',
  '                ',
  '     gggggg     ',
  '   ggGGGGGGgg   ',
  '  ggGGLLLLGGgg  ',
  ' ggGGLLGGLLGGgg ',
  ' gGGLLGGGGLLGGg ',
  ' gGGGLLGGLLGGGg ',
  ' ggGGGLLLLGGGgg ',
  '  ggGGGGGGGGgg  ',
  '   gggggggggg   ',
  '  WWWWWWWWWWWW  ',
  '   WWWWWWWWWW   ',
  '                ',
  '                ',
]

export const Mushroom: Frame = [
  '                ',
  '    KKKKKKKK    ',
  '  KKRRRRRRRRKK  ',
  ' KRRWWRRRRWWRRK ',
  ' KRWWWWRRWWWWRK ',
  'KRRWWWWRRWWWWRRK',
  'KRRRWWRRRRWWRRRK',
  'KRRRRRRRRRRRRRRK',
  'KKRRRRRRRRRRRRKK',
  '  KSSSSSSSSSSK  ',
  '  KSKSSSSSSKSK  ',
  '  KSSSSSSSSSSK  ',
  '  KSSSSSSSSSSK  ',
  '  KSSSSSSSSSSK  ',
  '   KKKKKKKKKK   ',
  '                ',
]
